#!/bin/bash -l
#PBS -l walltime=3:00:00
#PBS -l mem=1gb
#PBS -l nodes=1:ppn=1
#PBS -M yan.zhao1@student.kuleuven.be
#PBS -m eab
#PBS -A lp_joris_vermeesch_c1
##[VERSION] pika 16.08 
##[HELP] This tool will create a qc report of the fastq files
##[HELP] This script is multithreaded
##[HELP] This script runs between 1 and 10 minutes per fastq file
##
##[HOWTO] #FASTQC
##[HOWTO] #start the module:
##[HOWTO] qsub step0_fastqc_old.pbs

#setting all parameters (these could be changed)

PROJECT_DIR="/lustre1/project/stg_00019/research/yan/microhap/microhap11_CC117_control";
SAMPLE_DIR="/lustre1/project/stg_00019/margot_research/220301_Microhaps_CC117spikein_Mar22";
OUTPUT_DIR="$PROJECT_DIR/step0_fastqc_old";


cd $SAMPLE_DIR;

for i in `ls *.R?.fastq.gz`;
do
	files="$files $i";
done

mkdir -p $OUTPUT_DIR;

module load FastQC/0.11.8-Java-1.8.0_162

fastqc -o $OUTPUT_DIR -t 15 $files;

